backend/nirwals/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/17)

Resample method

---

backend/nirwals/configure/data/spectrum.py
backend/nirwals/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/18)

Moving read csv

---

backend/nirwals/configure/data/throughput.py
backend/nirwals/views.py
react/src/components/instrument/InstrumentConfigurationPanel.tsx
react/src/components/utils.ts
react/src/services.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/21)

Making Thoughtput form data reusable

---

react/src/App.tsx
react/src/components/Simulator.tsx
react/src/components/instrument/InstrumentConfigurationPanel.tsx
react/src/components/plots/PlotOptions.ts
react/src/components/spectrum/SpectrumGenerationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/23)

Add sky background plot

---

react/src/components/Simulator.tsx
react/src/components/plots/PlotOptions.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/24)

Using Scientific notation on the y-axes

---

react/src/components/plots/PlotOptions.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/26)

Science notation Fix

---

README.md
backend/backend/settings.py
backend/requirements.txt
docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/36)

Use environment variables

---

backend/Dockerfile
backend/requirements.txt
docker-compose.yml
frontend/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/38)

Use gunicorn and run as non-root

---

deployment/deploy-simulator.sh
frontend/src/components/Simulator.tsx
frontend/src/components/spectrum/SpectrumGenerationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/43)

Fix some linting issues

---

deployment/deploy-simulator.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/45)

Do not prune Docker images and containers

---

backend/nirwals/configure/data/throughput.py
frontend/src/components/instrument/InstrumentConfigurationPanel.tsx
frontend/src/components/instrument/SpectroscopyConfigurationPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/46)

Update the instrument configuration tab

---

backend/nirwals/views.py
frontend/src/components/spectrum/SpectrumGenerationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/52)

Reduce transferred data

---

docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/54)

Always restart containers

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/56)

Add instructions for configuring nginx on the deployment server

---

frontend/src/components/exposure/gain-panel/CustomGainPanel.tsx
frontend/src/components/exposure/gain-panel/GainPanel.tsx
frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/67)

Add a „Gain“ label

---

frontend/src/App.tsx
frontend/src/components/spectrum/BlackbodyPanel.tsx
frontend/src/components/spectrum/EarthPanel.tsx
frontend/src/components/spectrum/EmissionLinePanel.tsx
frontend/src/components/spectrum/GalaxyPanel.tsx
frontend/src/components/spectrum/MoonPanel.tsx
frontend/src/components/spectrum/SourceForm.tsx
frontend/src/components/spectrum/SpectrumForm.tsx
frontend/src/components/spectrum/SpectrumGenerationTab.tsx
frontend/src/components/spectrum/SpectrumPlotOptionsPanel.tsx
frontend/src/components/spectrum/SpectrumSelector.tsx
frontend/src/components/spectrum/SunPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/74)

Reformatting the form

---

frontend/src/components/exposure/query-panel/ExposureTimeQueryTab.tsx

Resolves #63.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/73)

Allow float values for the SNR

---

frontend/src/components/Simulator.tsx

Resolves #71.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/72)

Add a link to the documentation

---

deployment/deploy-simulator.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/69)

Update the deployment script

---

backend/nirwals/configuration.py
backend/nirwals/physics/exposure.py
backend/nirwals/tests/test_exposure.py
backend/nirwals/tests/utils.py
frontend/src/components/exposure/sampling-panel/SamplingPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/76)

Renaming Sampling Type to Sampling Mode

---

frontend/src/App.tsx
frontend/src/components/Simulator.tsx
frontend/src/components/exposure/ExposurePanel.tsx
frontend/src/components/exposure/gain-panel/CustomGainPanel.tsx
frontend/src/components/exposure/gain-panel/GainPanel.tsx
frontend/src/components/exposure/gain-panel/GainSelector.tsx
frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx
frontend/src/components/exposure/query-panel/ExposureTimeQueryTab.tsx
frontend/src/components/exposure/query-panel/QueryTabs.tsx
frontend/src/components/exposure/query-panel/SNRQueryTab.tsx
frontend/src/components/exposure/sampling-panel/SamplingPanel.tsx
frontend/src/components/instrument/InstrumentConfigurationPanel.tsx
frontend/src/components/instrument/SpectroscopyConfigurationPanel.tsx
frontend/src/components/plots/PlotOptions.ts
frontend/src/components/plots/linePlot.css
frontend/src/components/spectrum/BlackbodyPanel.tsx
frontend/src/components/spectrum/EarthPanel.tsx
frontend/src/components/spectrum/EmissionLinePanel.tsx
frontend/src/components/spectrum/GalaxyPanel.tsx
frontend/src/components/spectrum/SourceForm.tsx
frontend/src/components/spectrum/SpectrumGenerationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/75)

making the display looks the same and adding units

---

backend/nirwals/configuration.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/82)

Update expected filter name

---

backend/nirwals/configuration.py
frontend/src/components/spectrum/GalaxyPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/80)

Add "with emission lines" property for galaxy source

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Simulator.tsx
frontend/src/components/exposure/ExposureTab.tsx
frontend/src/components/exposure/gain-panel/GainPanel.tsx
frontend/src/components/exposure/query-panel/QueryTabs.tsx
frontend/src/components/exposure/sampling-panel/SamplingPanel.tsx
frontend/src/components/instrument/InstrumentConfigurationTab.tsx
frontend/src/components/plots/ExposurePlot.tsx
frontend/src/components/plots/LinePlot.tsx
frontend/src/components/plots/linePlot.css
frontend/src/components/spectrum/SpectrumGenerationTab.tsx
frontend/tailwind.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/77)

Setting plots to outdated

---

backend/nirwals/configuration.py
frontend/src/components/instrument/InstrumentConfigurationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/94)

Properly handle filter value

---

backend/nirwals/physics/exposure.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/81)

Extrapolate observation for non-overlapping bandpass and source spectrum

---

backend/nirwals/physics/bandpass.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/nir-simulator/96)

updating throughput fudge factor
